//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRecipeBook.Exception {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessagesException {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessagesException() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyRecipeBook.Exception.ResourceMessagesException", typeof(ResourceMessagesException).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error..
        /// </summary>
        public static string UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! This request needs an access token..
        /// </summary>
        public static string VALIDATION_ACCESS_TOKEN_REQUIRED {
            get {
                return ResourceManager.GetString("VALIDATION_ACCESS_TOKEN_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! You must add at least one dish type..
        /// </summary>
        public static string VALIDATION_AT_LEAST_ONE_DISH_TYPE {
            get {
                return ResourceManager.GetString("VALIDATION_AT_LEAST_ONE_DISH_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! You must add at least one ingredient..
        /// </summary>
        public static string VALIDATION_AT_LEAST_ONE_INGREDIENT {
            get {
                return ResourceManager.GetString("VALIDATION_AT_LEAST_ONE_INGREDIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! You must add at least one instruction..
        /// </summary>
        public static string VALIDATION_AT_LEAST_ONE_INSTRUCTION {
            get {
                return ResourceManager.GetString("VALIDATION_AT_LEAST_ONE_INSTRUCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! The selected cook time is not valid..
        /// </summary>
        public static string VALIDATION_COOK_TIME_INVALID {
            get {
                return ResourceManager.GetString("VALIDATION_COOK_TIME_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password is incorrect..
        /// </summary>
        public static string VALIDATION_CURRENT_PASSWORD {
            get {
                return ResourceManager.GetString("VALIDATION_CURRENT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! One of the selected dish types is not valid..
        /// </summary>
        public static string VALIDATION_DISH_TYPE_INVALID {
            get {
                return ResourceManager.GetString("VALIDATION_DISH_TYPE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! This email is already in use..
        /// </summary>
        public static string VALIDATION_EMAIL_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("VALIDATION_EMAIL_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! That email doesn’t look right..
        /// </summary>
        public static string VALIDATION_EMAIL_INVALID {
            get {
                return ResourceManager.GetString("VALIDATION_EMAIL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Email is required..
        /// </summary>
        public static string VALIDATION_EMAIL_REQUIRED {
            get {
                return ResourceManager.GetString("VALIDATION_EMAIL_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Ingredient cannot be empty..
        /// </summary>
        public static string VALIDATION_INGREDIENT_EMPTY {
            get {
                return ResourceManager.GetString("VALIDATION_INGREDIENT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Ingredient must be at most 250 characters long..
        /// </summary>
        public static string VALIDATION_INGREDIENT_MAX_LENGTH {
            get {
                return ResourceManager.GetString("VALIDATION_INGREDIENT_MAX_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Instruction description must be at most 2000 characters long..
        /// </summary>
        public static string VALIDATION_INSTRUCTION_DESCRIPTION_MAX_LENGTH {
            get {
                return ResourceManager.GetString("VALIDATION_INSTRUCTION_DESCRIPTION_MAX_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Instruction description is required..
        /// </summary>
        public static string VALIDATION_INSTRUCTION_DESCRIPTION_REQUIRED {
            get {
                return ResourceManager.GetString("VALIDATION_INSTRUCTION_DESCRIPTION_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Two or more instructions have the same order..
        /// </summary>
        public static string VALIDATION_INSTRUCTION_ORDER_DUPLICATED {
            get {
                return ResourceManager.GetString("VALIDATION_INSTRUCTION_ORDER_DUPLICATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Instruction order must be greater than zero..
        /// </summary>
        public static string VALIDATION_INSTRUCTION_ORDER_INVALID {
            get {
                return ResourceManager.GetString("VALIDATION_INSTRUCTION_ORDER_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Invalid email or password..
        /// </summary>
        public static string VALIDATION_LOGIN_INVALID {
            get {
                return ResourceManager.GetString("VALIDATION_LOGIN_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Name is required..
        /// </summary>
        public static string VALIDATION_NAME_REQUIRED {
            get {
                return ResourceManager.GetString("VALIDATION_NAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Password must be at least 6 characters long..
        /// </summary>
        public static string VALIDATION_PASSWORD_MIN_LENGTH {
            get {
                return ResourceManager.GetString("VALIDATION_PASSWORD_MIN_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Password is required..
        /// </summary>
        public static string VALIDATION_PASSWORD_REQUIRED {
            get {
                return ResourceManager.GetString("VALIDATION_PASSWORD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! We couldn’t find this recipe..
        /// </summary>
        public static string VALIDATION_RECIPE_NOT_FOUND {
            get {
                return ResourceManager.GetString("VALIDATION_RECIPE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! You don’t have access to this resource..
        /// </summary>
        public static string VALIDATION_RESOURCE_ACCESS_DENIED {
            get {
                return ResourceManager.GetString("VALIDATION_RESOURCE_ACCESS_DENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Title must be at most 250 characters long..
        /// </summary>
        public static string VALIDATION_TITLE_MAX_LENGTH {
            get {
                return ResourceManager.GetString("VALIDATION_TITLE_MAX_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Title is required..
        /// </summary>
        public static string VALIDATION_TITLE_REQUIRED {
            get {
                return ResourceManager.GetString("VALIDATION_TITLE_REQUIRED", resourceCulture);
            }
        }
    }
}
