trigger:
- master

variables:
  dockerRegistryServiceConnection: 'bd96d70c-afcd-41ce-9b18-627db2176826'
  imageRepository: 'apimyrecipebook'
  containerRegistry: 'apimyrecipebook.azurecr.io'
  dockerfilePath: 'Dockerfile'
  tag: '$(Build.BuildId)'

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: DownloadSecureFile@1
  displayName: Download appsettings.json
  name: appsettings
  inputs:
    secureFile: 'appsettings.Production.json'

- script: |
    cp $(appsettings.secureFilePath) src/Backend/MyRecipeBook.API

- task: Docker@2
  displayName: Build and push an image to container registry
  inputs:
    command: buildAndPush
    repository: $(imageRepository)
    dockerfile: $(dockerfilePath)
    containerRegistry: $(dockerRegistryServiceConnection)
    tags: |
      latest
      $(tag)